# Generated by Django 4.2.11 on 2024-05-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectangle',
            name='color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
