# Generated by Django 4.2.11 on 2024-05-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rectangle_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='content',
            new_name='rectangles',
        ),
    ]
