/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Imagedialog: typeof import('./src/components/imagedialog.vue')['default']
    Imagelist: typeof import('./src/components/imagelist.vue')['default']
    New_notifier: typeof import('./src/components/new_notifier.vue')['default']
    Notifier: typeof import('./src/components/notifier.vue')['default']
  }
}
